---
- name: Install Docker on Debian
  hosts: all
  become: true

  tasks:
    - name: Add Docker's official GPG key
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg

    - name: Create directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
      notify: Set permissions for GPG key

    - name: Set appropriate permissions for the GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'
      when: "'/etc/apt/keyrings/docker.gpg' is file"

    - name: Add Docker repository to Apt sources
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: |
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      notify: Update apt cache

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

  handlers:
    - name: Set permissions for GPG key
      debug:
        msg: "Setting permissions for the GPG key"
