- name: Setup Docker on Ubuntu Server 22.04
  hosts: all
  become: true
  remote_user: root

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present
    filename: docker

- name: Install Docker 23.0.1-1
  ansible.builtin.apt:
    name:
      - docker-ce=5:23.0.1-1~ubuntu.22.04~jammy
      - docker-ce-cli=5:23.0.1-1~ubuntu.22.04~jammy
      - containerd.io
    state: present
    update_cache: true

- name: Setup docker user
  ansible.builtin.user:
    name: docker
    groups: 'docker'
    append: true
    sudo_user: yes

- name: Install Docker module for Python
  ansible.builtin.pip:
    name: docker

- name: Install Docker Compose from repository
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true
