---
- name: Working with Windows Server
  hosts: win
  tasks:
    - name: Create Directory
      win_file:
        path: C:\Temp\demofolder
        state: directory

    - name: Create file
      win_file:
        path: C:\Temp\demofolder\windemo.txt
        state: touch
