---
- name: reboot machine
  hosts: all
  become: yes
  tasks:
    - name: reboot machine
      reboot:
        reboot_timeout: 3600
    - name: Send reboot notification to Telegram
      uri:
        url: 'https://api.telegram.org/bot6167093497:AAFHVoxKksDFktFJ5cd2X91lmSPbMG6p0MI/sendMessage'
        method: POST
        body_format: json
        body:
          chat_id: '1104775987'
          text: 'Reboot initiated on {{ inventory_hostname }}'
        status_code: 200
      delegate_to: localhost
