---
- name: check disk space
  hosts: all
  tasks:
    - name: get disk usage
      command: df -h
      register: disk_usage
    - name: check disk space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage
    - name: Send disk space notification to Telegram
      uri:
        url: 'https://api.telegram.org/bot6167093497:AAFHVoxKksDFktFJ5cd2X91lmSPbMG6p0MI/sendMessage'
        method: POST
        body_format: json
        body:
          chat_id: '1104775987'
          text: |
            Disk space check on {{ inventory_hostname }}
            Disk Usage: {{ disk_usage.stdout }}
        status_code: 200
      delegate_to: localhost
