---
- name: Check Connectivity and Report
  hosts: all
  gather_facts: false
  tasks:
    - name: 01 - Test Connectivity
      ansible.builtin.ping:
      register: connectivity
      ignore_unreachable: true

    - name: 02 - Save summary of connectivity check
      ansible.builtin.set_fact:
        summary: "{{ (summary | default([])) + [ item + ';' + _result ] }}"
      vars:
        _result: "{{ (hostvars[item]['connectivity']['msg'] | default('OK')).splitlines() | join()  }}"
      loop: '{{ ansible_play_hosts }}'
      delegate_to: localhost
      run_once: true

    - name: 03 - Show result
      ansible.builtin.debug:
        msg: '{{ summary }}'
      delegate_to: localhost
      run_once: true

    - name: 04 - Send result to Telegram
      ansible.builtin.uri:
        url: "https://api.telegram.org/bot6167093497:AAFHVoxKksDFktFJ5cd2X91lmSPbMG6p0MI/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-1002431095379"
          text: "Connectivity Test Results:\n{{ summary | sort | join('\n') }}"
        headers:
          Content-Type: "application/json"
      delegate_to: localhost
      run_once: true