---
- name: Check Connectivity and Report
  hosts: all
  gather_facts: false
  tasks:
    - name: 01 - Test Connectivity
      ansible.builtin.ping:
      register: connectivity
      ignore_unreachable: true

    - name: 02 - Save summary of connectivity check
      ansible.builtin.set_fact:
        summary: "{{ (summary | default([])) + [ item + ';' + _result ] }}"
      vars:
        _result: "{{ (hostvars[item]['connectivity']['msg'] | default('OK')).splitlines() | join()  }}"
      loop: '{{ ansible_play_hosts }}'
      delegate_to: localhost
      run_once: true

    - name: 03 - Show result
      ansible.builtin.debug:
        msg: '{{ summary }}'
      delegate_to: localhost
      run_once: true

    - name: 04 - Send result to Telegram
      ansible.builtin.uri:
        url: "https://api.telegram.org/bot6167093497:AAFHVoxKksDFktFJ5cd2X91lmSPbMG6p0MI/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-1002431095379"
          text: "Connectivity Test Results:\n{{ summary | sort | join('\n') }}"
        headers:
          Content-Type: "application/json"
      delegate_to: localhost
      run_once: true

- name: Check and restart MySQL if down
  hosts: all
  become: yes
  tasks:
    - name: Check if MySQL service is running
      become: true
      shell: "systemctl is-active mysql"
      register: mysql_status
      failed_when: false

    - name: Debug MySQL status
      debug:
        msg: "MySQL status: {{ mysql_status.stdout }}"

    - name: Restart MySQL service if down
      become: true
      service:
        name: mysql
        state: restarted
      when: mysql_status.stdout != "active"

    - name: Send notification to Telegram if MySQL was down
      uri:
        url: "https://api.telegram.org/bot6167093497:AAFHVoxKksDFktFJ5cd2X91lmSPbMG6p0MI/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-1002431095379"
          text: >-
            MySQL service was found down and has been restarted on {{ inventory_hostname }}.
        status_code: 200
      when: mysql_status.stdout != "active"
      delegate_to: localhost

    - name: Send notification to Telegram if MySQL is running
      uri:
        url: "https://api.telegram.org/bot6167093497:AAFHVoxKksDFktFJ5cd2X91lmSPbMG6p0MI/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-1002431095379"
          text: >-
            MySQL service is running normally on {{ inventory_hostname }}.
        status_code: 200
      when: mysql_status.stdout == "active"
      delegate_to: localhost
