- name: Add SSH key to remote server
  hosts: all
  become: yes

  tasks:
    - name: Add SSH key to authorized_keys
      authorized_key:
        user: server
        key: "{{ lookup('file', '/home/server/.ssh/id_rsa.pub') }}"
        state: present
