---
- name: Setup Prometheus Node Exporter
  hosts: all
  become: yes
  tasks:
    - name: Download Node Exporter archive
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-1.7.0.tar.gz"

    - name: Extract Node Exporter archive
      ansible.builtin.command:
        cmd: "tar xvfz /tmp/node_exporter-1.7.0.tar.gz -C /tmp"

    - name: Move Node Exporter binary to /usr/local/bin
      ansible.builtin.command:
        cmd: "sudo mv /tmp/node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin"

    - name: Remove extracted directory
      ansible.builtin.command:
        cmd: "sudo rm -r /tmp/node_exporter*"

    - name: Start Node Exporter service
      ansible.builtin.command:
        cmd: "node_exporter"

    - name: Create node_exporter user
      ansible.builtin.command:
        cmd: "sudo useradd -rs /bin/false node_exporter"

    - name: Create systemd service file for Node Exporter
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          Restart=on-failure
          RestartSec=5s
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/node_exporter.service"
        owner: root
        group: root
        mode: "0644"

    - name: Enable Node Exporter service
      ansible.builtin.command:
        cmd: "sudo systemctl enable node_exporter"

    - name: Reload systemd daemon and start Node Exporter service
      ansible.builtin.command:
        cmd: "sudo systemctl daemon-reload && sudo systemctl start node_exporter && sudo systemctl status node_exporter"
