- name: Setup Prometheus Node Exporter
  hosts: all
  become: yes
  tasks:
    - name: Download Node Exporter archive
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-1.7.0.tar.gz"

    - name: Extract Node Exporter archive
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-1.7.0.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move Node Exporter binary to /usr/local/bin
      ansible.builtin.command:
        cmd: "sudo mv /tmp/node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin"

    - name: Remove extracted directory
      ansible.builtin.file:
        path: "/tmp/node_exporter-1.7.0.linux-amd64"
        state: absent
        recurse: yes

    - name: Create node_exporter user
      ansible.builtin.user:
        name: node_exporter
        system: yes
        shell: /bin/false

    - name: Create systemd service file for Node Exporter
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          Restart=on-failure
          RestartSec=5s
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/node_exporter.service"
        owner: root
        group: root
        mode: "0644"

    - name: Enable Node Exporter service
      ansible.builtin.service:
        name: node_exporter
        enabled: yes

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start Node Exporter service
      ansible.builtin.service:
        name: node_exporter
        state: started

    - name: Check Node Exporter service status
      ansible.builtin.systemd:
        name: node_exporter
        state: started
