- name: Add SSH key to remote server
  hosts: all
  become: yes
  
  tasks:
    - name: Create user
      user:
        name: ansible
        generate_ssh_key: true
        createhome: yes
        shell: /bin/bash
        state: present

    - name: Add SSH key to authorized_keys
      authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/server/.ssh/id_rsa.pub') }}"
        state: present

    - name: Allow user to execute sudo without password
      lineinfile:
        dest: /etc/sudoers
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
        state: present
